module.exports = {
  input: {
    fontFamily: 'Quicksand-SemiBold',
    fontSize: 15,
    paddingLeft: 20,
    height: 45,
    borderColor: 'lightgray',
    borderWidth: 1,
    width: '100%',
    zIndex: 2,
  },
  msg: {
    fontFamily: 'Quicksand-SemiBold',
    fontSize: 15,
    marginLeft: 15,
    marginRight: 15,
    textAlign: 'right',
    backgroundColor: 'lightgray',
    alignSelf: 'flex-end',
    // color: 'white',
    paddingTop: 10,
    paddingBottom: 10,
    paddingLeft: 15,
    paddingRight: 15,
    borderRadius: 10,
    marginTop: 10,
  },
  msg2: {
    fontFamily: 'Quicksand-SemiBold',
    fontSize: 15,
    marginLeft: 15,
    marginRight: 15,
    textAlign: 'right',
    backgroundColor: '#a3f7bf',
    alignSelf: 'flex-start',
    // color: 'white',
    paddingTop: 10,
    paddingBottom: 10,
    paddingLeft: 15,
    paddingRight: 15,
    borderRadius: 10,
    marginTop: 10,

},
  msgContainer: {
    padding: 10,
    backgroundColor: 'red',
  }
}
